import { APPOINTMENT_STATUS } from './constants'
export const applicants = [
  {
    applicantId: 'appl_1',
    fullName: 'Friedrich Heinrich',
    phoneNumber: '+49 146 344 23811',
    email: 'friedrich.heinrich@gmail.com',
    appointmentStatus: APPOINTMENT_STATUS.appointmentSet,
    appointmentDate: '22 JULY 14:00',
    viewedOn: null,
    hasBeenViewed: false,
    offeredBid: null,
  },
  {
    applicantId: 'appl_2',
    fullName: 'Hans Ulrich',
    phoneNumber: '+49 146 344 23811',
    email: 'friedrich.heinrich@gmail.com',
    appointmentStatus: APPOINTMENT_STATUS.appointmentSet,
    appointmentDate: '22 JULY 14:00',
    viewedOn: null,
    hasBeenViewed: false,
    offeredBid: null,
  },
  {
    applicantId: 'appl_3',
    fullName: 'Karlheinz Brandenburg',
    phoneNumber: '+49 146 344 23811',
    email: 'friedrich.heinrich@gmail.com',
    appointmentStatus: APPOINTMENT_STATUS.viewed,
    appointmentDate: '22 JULY 14:00',
    viewedOn: null,
    hasBeenViewed: false,
    offeredBid: null,
  },
  {
    applicantId: 'appl_4',
    fullName: 'Karlheinz Brandenburg',
    phoneNumber: '+49 146 344 23811',
    email: 'friedrich.heinrich@gmail.com',
    appointmentStatus: APPOINTMENT_STATUS.viewed,
    appointmentDate: '22 JULY 14:00',
    viewedOn: '11 June 11:30',
    hasBeenViewed: true,
    offeredBid: '250.000€',
  },
  {
    applicantId: 'appl_5',
    fullName: 'Karlheinz Brandenburg',
    phoneNumber: '+49 146 344 23811',
    email: 'friedrich.heinrich@gmail.com',
    appointmentStatus: APPOINTMENT_STATUS.viewed,
    appointmentDate: '22 JULY 14:00',
    viewedOn: '11 June 11:30',
    hasBeenViewed: true,
    offeredBid: '250.000€',
  },
  {
    applicantId: 'appl_6',
    fullName: 'Karlheinz Brandenburg',
    phoneNumber: '+49 146 344 23811',
    email: 'friedrich.heinrich@gmail.com',
    appointmentStatus: APPOINTMENT_STATUS.viewed,
    appointmentDate: '22 JULY 14:00',
    viewedOn: '11 June 11:30',
    hasBeenViewed: true,
    offeredBid: '250.000€',
  },
]

export const status = {
  total: 25,
  new: 10,
  viewed: 5,
  appointments: 3,
  others: 6,
}
